{{- if .Values.relay.enable }}
apiVersion: v1
kind: Service
metadata:
  name: relay
  labels:
    app: relay
spec:
  type: ClusterIP
  selector:
    app: relay
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
{{- end }}
