{{- if .Values.signal.enable }}
apiVersion: v1
kind: Service
metadata:
  name: signal
  labels:
    app: signal
spec:
  type: ClusterIP
  selector:
    app: signal
  ports:
    - name: grpc
      port: 443
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
{{- end }}
